apiVersion: apps/v1
kind: Deployment

metadata:
  name: customerapi

spec:
  replicas: 1

  selector:
    matchLabels:
      app: customerapi

  template:

    metadata:
      labels:
        app: customerapi

    spec:

      containers:

        - name: customerapi

          image: varshithreddy144/customerapi:25726763095

          ports:
            - containerPort: 7003