apiVersion: v1
kind: Service

metadata:
  name: customerapi-service
  namespace: default

spec:
  selector:
    app: customerapi

  ports:
    - protocol: TCP
      port: 80
      targetPort: 7003

  type: ClusterIP