apiVersion: apps/v1

kind: Deployment

metadata:
  name: productapi

spec:
  replicas: 5

  selector:
    matchLabels:
      app: productapi

  template:

    metadata:
      labels:
        app: productapi

    spec:

      containers:

        - name: productapi

          image: varshithreddy144/productapi:25675754938

          ports:
            - containerPort: 7001