apiVersion: apps/v1

kind: Deployment

metadata:
  name: cartapi

spec:
  replicas: 6

  selector:
    matchLabels:
      app: cartapi

  template:

    metadata:
      labels:
        app: cartapi

    spec:

      containers:

        - name: cartapi

          image: varshithreddy144/cartapi:25628992789

          ports:
            - containerPort: 7004
