apiVersion: v1
kind: Service

metadata:
  name: cartapi-service
  namespace: test

spec:
  selector:
    app: cartapi

  ports:
    - protocol: TCP
      port: 80
      targetPort: 7004

  type: ClusterIP