apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ecommerce-ingress
  namespace: default

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:

          # =========================
          # ADMIN API
          # =========================
          - path: /admin(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: adminapi-service
                port:
                  number: 80

          # =========================
          # AUTH USER API
          # =========================
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: authuser-service
                port:
                  number: 80

          # =========================
          # CART API
          # =========================
          - path: /cart(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: cartapi-service
                port:
                  number: 80

          # =========================
          # CUSTOMER API
          # Handles:
          # /api/customer/*
          # /api/address/*
          # =========================
          - path: /customer(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: customerapi-service
                port:
                  number: 80

          # =========================
          # ORDER API
          # =========================
          - path: /order(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: orderapi-service
                port:
                  number: 80

          # =========================
          # PRODUCT API
          # =========================
          - path: /product(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: productapi-service
                port:
                  number: 80