apiVersion: apps/v1

kind: Deployment

metadata:
  name: authuser

spec:
  replicas: 1

  selector:
    matchLabels:
      app: authuser

  template:

    metadata:
      labels:
        app: authuser

    spec:

      containers:

        - name: authuser

          image: varshithreddy144/authuser:25675755007

          ports:
            - containerPort: 5000