spring.application.name=authuser-service

server.port=5000

# ===============================
# MYSQL DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://database-1.criu8o0oyn96.eu-north-1.rds.amazonaws.com:3306/ecommerce
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# KUBERNETES DISCOVERY
# ===============================

spring.cloud.kubernetes.discovery.enabled=true
spring.cloud.kubernetes.loadbalancer.mode=service

# ===============================
# CONNECTION POOL
# ===============================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
