spring.application.name=authuser-service

server.port=5000

# ===============================
# H2 DATABASE
# ===============================

spring.datasource.url=jdbc:h2:mem:securitydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# KUBERNETES DISCOVERY
# ===============================

spring.cloud.kubernetes.discovery.enabled=true
spring.cloud.kubernetes.loadbalancer.mode=service
