spring.application.name=adminapi


# ===============================
# H2 DATABASE
# ===============================

spring.datasource.url=jdbc:h2:mem:admindb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true


# ===============================
# SERVER
# ===============================

server.port=7002


# ===============================
# FORWARDED HEADERS
# ===============================

server.forward-headers-strategy=framework


# ===============================
# SWAGGER / OPENAPI
# ===============================

springdoc.api-docs.servers[0].url=http://localhost:7002
springdoc.api-docs.servers[0].description=Admin API