spring.application.name=adminapi-service

server.port=7002

# ===============================

# MYSQL DATABASE

# ===============================

spring.datasource.url=jdbc:mysql://database-1.criu8o0oyn96.eu-north-1.rds.amazonaws.com:3306/ecommerce
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================

# HIKARI CONNECTION POOL

# ===============================

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# ===============================

# KUBERNETES DISCOVERY

# ===============================

spring.cloud.kubernetes.discovery.enabled=true
spring.cloud.kubernetes.loadbalancer.mode=service


