spring.application.name=adminapi

# ===============================
# MYSQL DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://database-1.criu8o0oyn96.eu-north-1.rds.amazonaws.com:3306/ecommerce
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================

server.port=7002

# ===============================
# FORWARDED HEADERS
# ===============================

server.forward-headers-strategy=framework

# ===============================
# SWAGGER / OPENAPI
# ===============================

springdoc.api-docs.servers[0].url=http://localhost:7002
springdoc.api-docs.servers[0].description=Admin API