apiVersion: apps/v1

kind: Deployment

metadata:
  name: orderapi

spec:
  replicas: 1

  selector:
    matchLabels:
      app: orderapi

  template:

    metadata:
      labels:
        app: orderapi

    spec:

      containers:

        - name: orderapi

          image: varshithreddy144/orderapi:25719014225

          ports:
            - containerPort: 7005