apiVersion: v1
kind: Service

metadata:
  name: orderapi-service
  namespace: default

spec:
  selector:
    app: orderapi

  ports:
    - protocol: TCP
      port: 80
      targetPort: 7005

  type: ClusterIP