apiVersion: apps/v1

kind: Deployment

metadata:
  name: adminapi

spec:
  replicas: 3

  selector:
    matchLabels:
      app: adminapi

  template:

    metadata:
      labels:
        app: adminapi

    spec:

      containers:

        - name: adminapi

          image: varshithreddy144/adminapi:25675754990

          ports:
            - containerPort: 7002
