apiVersion: v1
kind: Service

metadata:
  name: adminapi-service
  namespace: default

spec:
  selector:
    app: adminapi

  ports:
    - protocol: TCP
      port: 80
      targetPort: 7002

  type: ClusterIP