spring.application.name=cartapi-service

spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=7004

management.tracing.enabled=false

# ===============================
# KUBERNETES DISCOVERY
# ===============================

spring.cloud.kubernetes.discovery.enabled=true
spring.cloud.kubernetes.loadbalancer.mode=service